"""where box2

Revision ID: 5a89f251275c
Revises: 64c9fa086117
Create Date: 2018-11-22 11:37:02.073495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a89f251275c'
down_revision = '64c9fa086117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'postPlace')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('postPlace', sa.VARCHAR(length=70), nullable=True))
    # ### end Alembic commands ###
