"""post blocks

Revision ID: 64c9fa086117
Revises: 3312523432c3
Create Date: 2018-11-22 10:42:31.053469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c9fa086117'
down_revision = '3312523432c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('postPlace', sa.String(length=70), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'postPlace')
    # ### end Alembic commands ###
